name: Makefile CI

on:
  schedule:
    - cron: "0 23 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}   # default GitHub token

    - name: init
      run: python -m venv venv

    - name: install
      run: pip install -r requirements.txt

    - name: activate
      run: . venv/bin/activate

    - name: config
      run: |
         git config user.name "GitHub Actions"
         git config user.email "actions@github.com"

    - name: run
      run: make

    - name: push
      run: |
        git commit -m "Automated update from workflow [skip ci]"
        git push
